version: '3.9'
services:
  app:
    build: .
    container_name: blindtest_app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    env_file:
      - .env
    restart: unless-stopped
  healthcheck:
    test: ["CMD", "node", "-e", "require('http').get('http://localhost:' + (process.env.PORT||3000) + '/health', r=>{process.exit(r.statusCode===200?0:1)}).on('error',()=>process.exit(1))"]
    interval: 30s
    timeout: 5s
    retries: 3
    start_period: 10s

