version: '3.9'
services:
  app:
    build: .
    container_name: blindtest_app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    env_file:
      - .env
    restart: unless-stopped
  healthcheck:
    test: ["CMD", "wget", "-qO-", "http://${HOST}:${PORT}/health"]
    interval: 30s
    timeout: 5s
    retries: 3
    start_period: 10s

