version: '3.9'
services:
  app:
    build: .
    container_name: blindtest_app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - ${PORT}
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
  healthcheck:
    test: ["CMD", "wget", "-qO-", "http://${HOST}:${PORT}/health"]
    interval: 30s
    timeout: 5s
    retries: 3
    start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: blindtest_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot:/etc/letsencrypt
      - ./data/letsencrypt:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot:/etc/letsencrypt
      - ./data/letsencrypt:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'
